= Codename One Project

{{ releasesUrl }}[Releases]

This is a multi-module maven project for building a Codename One application. Codename One applications written in Java and/or Kotlin, and are built as native apps and can be built and deployed to iOS, Android, Mac, Windows, Linux, and also to the Web.

== Getting Started

=== Java

If you plan to use Java as your primary language, https://shannah.github.io/cn1-maven-archetypes/cn1app-archetype-tutorial/getting-started.html[start here].

=== Kotlin

If you plan to use Kotlin as your primary language, https://shannah.github.io/cn1app-archetype-kotlin-template/getting-started.html[start here].


== Eclipse Users

IMPORTANT: If you use Eclipse as your IDE, **read this first**

The _tools/eclipse_ directory contains eclipse ".launch" files that will add common Maven goals as menu items inside Eclipse.

**After importing this project into Eclipse, you should import the launch files.**

== NetBeans Users

This project is a multi-module Maven project that was generated from a Maven archetype.

== IntelliJ Users

The project should work in IntelliJ out of the box.  No need to copy any files.

== Help and Support

See the https://www.codenameone.com[Codename One Web Site].

== DMG Releases

By default Mac releases use an installer.  You can optionally enable DMG releases also by setting the variable `JDEPLOY_CREATE_DMG=true` in your repository settings.
You will also need to define the following secrets:

. `MAC_DEVELOPER_ID` : Your email address for your Apple developer account.
. `MAC_DEVELOPER_CERTIFICATE_P12_BASE64` : A base64 encoding of your Mac developer certificate (p12)
. `MAC_DEVELOPER_CERTIFICATE_PASSWORD` : The password you used for your Mac developer certificate p12, when you exported it from your keychain.
. `MAC_NOTARIZATION_PASSWORD` : The application-specific password that you set for notarization in your Apple developer account.
